# 【硬链接模式的配置文件】：主要功能：监控下载目录，目录有变化时自动转移识别重命名，没有UI界面，但可以保留通知。建议体验全功能版本。
# 【配置注意要符合yaml语法，:号后有1个空格，不能使用全角标点符号】
app:
  # 这个配置不要改
  simple_mode: true
  # 【TMDB API KEY】：需要在https://www.themoviedb.org/申请，必须配置，否则无法识别媒体资源和重命名
  # 以下地址需要网络能够正常访问：api.themoviedb.org、images.weserv.nl、webservice.fanart.tv
  rmt_tmdbkey:
  # 【TMDB匹配模式】：normal、strict，normal模式下如使用文件名/种子名中的年份无法匹配到媒体信息，会去掉年份再匹配一次；strict模式则严格按文件中年份匹配
  # normal模式下会提升识别成功率，但也可能会导致误识别率增加；strict模式可以降低误识别率，但可能导致很多文件名/种子名中年份不正确的无法被识别（特别是剧集，需要是首播年份）
  rmt_match_mode: normal
  # 【设置代理】，themoviedb、fanart、telegram等将使用代理访问，http和https均需配置，可以是http也可以是socks5，但需要带http或socks5前缀，两项可以配置为一样，留空则不启用
  # 示例：'http://127.0.0.1:7890' 'socks5://127.0.0.1:8018'
  proxies:
    http:
    https:

# 【配置媒体库信息】
media:
  # 【媒体库电影文件存放目录】：支持配置多个目录，不同的硬盘需映射为不同的根目录，以更于程序区分
  movie_path:
    - '/mnt/media/电影'
  # 【媒体库电视剧文件存放目录】：支持配置多个目录，不同的硬盘需映射为不同的根目录，以更于程序区分
  tv_path:
    - '/mnt/media/电视剧'
  # 【媒体库动漫文件单独存放目录】：支持配置多个目录，不同的硬盘需映射为不同的根目录，以更于程序区分
  # 如果设置了该目录，则所有动漫电视剧都会识别为动漫并存放在该目录下，否则动漫电视剧会识别为电视剧并存放在电视剧目录分类下；动漫电影仍然在电影目录分类下
  anime_path:
    - '/mnt/media/动漫'
  # 【无法识别时转移存放的目录】：如有多个磁盘，需要对应配置多个目录，否则跨盘无法硬链接
  # 注意：如果你在sync区域配置了未识别目录，由会优先转移到对应未识别目录下，只有PT下载转移及sync未配置未识别目录时才会使用该目录
  unknown_path:
    - '/mnt/media/unknown'
  # 【二级分类开关】：电影/电视剧/动漫是否需要二级分类，启用二级分类后会在电影/电视剧/动漫目录下按二级分类名建立子目录
  # 此处配置分类的策略名，配置文件目录中需要有与策略名同名的.yaml配置文件
  # 默认策略default-category分类设置可参考"default-category.yaml"，分类参见README.MD说明
  # 如不需要启动分类，则该项配置为空
  category: 'default-category'
  # 【转移到媒体库的最小文件大小】：避免预告片/MV等影响识别，单位M
  min_filesize: 200
  # 【洗版开关】：如开启则新下载了更大的文件会覆盖媒体库目录中已有的文件
  filesize_cover: true

# 【配置消息通知服务】
message:
  # 【发送消息使用的渠道】：wechat、serverchan、telegram、bark，需在对应的配置区域配置。不使用的渠道配置可以留空或者删除。推荐使用wechat微信渠道。不设置则不启用消息服务
  msg_channel: wechat
  # 【Emby播放状态通知白名单】：配置了Emby webhooks插件回调时，用户播放媒体库中的媒体时会发送消息通知，本处配置哪些用户的设备不通知，避免打扰，配置格式：用户:设备名称，可用 - 增加多项
  webhook_ignore:
    - 'admin:xx的iPhone 12'
  # 【企业微信通知】：在企业微信https://work.weixin.qq.com/中申请和新增一个自建应用。配合微信的企业微信插件，可以直接在微信中查看本程序的消息以及控制程序运行，非常好用，推荐使用该渠道
  wechat:
    # corpid:每个企业都拥有唯一的corpid，获取此信息可在管理后台“我的企业”－“企业信息”下查看“企业ID”（需要有管理员权限）
    # corpsecret:自建应用secret。在管理后台->“应用与小程序”->“应用”->“自建”，点进某个应用，即可看到
    # agentid:每个应用都有唯一的agentid。在管理后台->“应用与小程序”->“应用”，点进某个应用，即可看到agentid
    # 具体不明白的参考企业微信的开发者中心
    corpid:
    corpsecret:
    agentid:
    # 【微信回调】：用于在微信中控制本程序，需要在企业微信https://work.weixin.qq.com/中设置自建应用的菜单等
    ## 配置步聚：
    # 1、在微信企业应用接收消息设置页面生成Token和EncodingAESKey并填入下面区域。
    # 2、重启本程序。
    # 3、在微信企业应用接收消息设置页面输入此地址：http(s)://ip:3000/wechat，需要有公网IP并做好端口转发，最好要有域名
    Token:
    EncodingAESKey:
  # 【Server酱消息通知】：填写ServerChan的API KEY，SCT类型，在https://sct.ftqq.com/中申请（非VIP貌似每日限制只能收到5条消息）
  serverchan:
    sckey:
  # 【Telegram通知】：填写Telegram bot机器人的信息，需要在Telegram中创建机器人
  telegram:
    # telegram机器人的Token，关注BotFather创建机器人
    telegram_token:
    # telegram中关注getuserID获取
    telegram_chat_id:
  # 【Bark通知】，手机上安装Bark客户端，Server可以使用默认的也可以自己搭建，自己搭建的更换为服务器地址和端口，格式：http(s)://IP:PORT
  bark:
    # 自己搭建请更换，否则保持默认
    server: https://api.day.app
    # Bark客户端生成的KEY
    apikey:

# 【配置文件夹监控】：文件夹内容发生变化时自动识别转移
sync:
  # 【监控目录列表】：监控目录有文件变化时会自动进行媒体识别、转移并命名
  # 可以配置多个，使用|分隔，按'源目录|目的目录|未识别目录'格式配置，源目录为需要同步的目录，目的目录为识别和改名后存放的目录，未识别目录为无法识别时转移的目录
  # 配置格式1：'源目录'，比如：'/mnt/pt'，源目录文件会自动识别是电影、电视剧或动漫并分别转移到media中配置的movie_path、tv_path、anime_path目录中，未识别的会转移到media中配置的unknown_path中
  # 配置格式2：'源目录|目的目录'，比如：'/mnt/pt_movie|mnt/emby_movie'，源目录中文件不会区分类型，均往目的目录转移，未识别的会转移到media中配置的unknown_path中
  # 配置格式3：'源目录|目的目录|未识别目录'，比如：'/mnt/pt_movie|mnt/emby_movie|emby_unknown'，源目录中文件不会区分类型，均往目的目录转移，未识别的会转移到未识别目录中
  # 配置格式4：'[源目录|目的目录]'，比如'[/mnt/pt_music|mnt/emby_music]'，即使用[]括起来代表这个目录不是影视文件，不需要进行识别和重命名，程序会对源目录下所有的文件全部硬链接到目的目录，不会有消息通知等功能
  # 一行的三个目录需要在同一个磁盘分区/共享目录中，有多个目录的，需要映射上级目录，源目录和目的目录为子目录，如果分开映射则可能发生跨盘的问题
  sync_path:
    - '/mnt/resiliosync/大片抢先看'
    - '/mnt/pt|/mnt/emby'
    - '/mnt/pt|/mnt/emby|/mnt/unknown'
    - '[/mnt/pt_music|mnt/emby_music]'
  # 【监控目录文件的转移方式】：link、copy、softlink，link即硬链接、softlink为软链接，copy为复制，均会重命名
  # link要求源目录和目的目录或媒体库目录在一个磁盘分区或者存储空间，Docker运行时link模式需要直接映射源目录和目的目录或媒体库目录的上级目录，否则docker可能仍然会认为是跨盘
  # softlink模式注意宿主机的源目录映射到docker容器中后要路径要一致，否则可能软链接成功但无法在宿主机使用
  sync_mod: link
  # 【监控目录操作系统类型】：windows、linux。如果是windows，目录同步功能性能会比较差，会导致NAS不能休眠，除非挂载的windows的远程共享目录，否则建议设置为linux
  nas_sys: linux